### ISSUE TITLE
Are you actually maintaining these scripts?

### ISSUE THREAD

**Issue by zuzzurro** [Devbrat-Dev/podman_scripts#1]
Just asking, because I don't think they work with the latest Immich

**Comment by Devbrat-Dev** [comment]
Could you please let me know which Linux distribution you are using?

**Comment by zuzzurro** [comment]
Sure... I'm running a mix of Fedora 41 and Rawhide. Sorry if my question was too vague, I was not sure if you would respond at all... It's been a while since I tried using your scripts that initially worked very well indeed but broke a bit later. Let me find the error and I'll post it here.

**Comment by zuzzurro** [comment]
Mmmh, I tried running make install again on my rawhide arm small server and it looks like it works... I was under the impression that it had stopped working after some rebasing my local immich repo but maybe it was on another machine. I'll keep you posted.

**Comment by Devbrat-Dev** [comment]
Thank you for the update! I'm currently updating the scripts to ensure better compatibility with the latest version of Immich, especially considering the breaking changes in v1.118.0.

Out of curiosity, are you using hardware acceleration on your ARM server? You can refer to the [ARM NN (Mali)](https://immich.app/docs/features/ml-hardware-acceleration/#supported-backends) documentation for more details.

**Comment by zuzzurro** [comment]
Hi. So I pulled your latest changes and I will test them as soon as I have a bit of time. I think my issues were related exactly to the breaking changes in v.1.118.0 if I remember well.
Related to the hw acceleration I need to check if it's supported when using the upstream kernel and the panthor driver...

**Comment by zuzzurro** [comment]
In the previous version I had to add a ",z" to the immich-server.container Volume definition, like this:

`
Volume=/YYY:/mnt/external/Pictures:ro,z
`

How would I do this in the new version short of changing the template?

**Comment by Devbrat-Dev** [comment]
You can do that by editing the file `immich/config/container-templates/immich-server.txt` and modifying this line:

```plaintext
# External path to media 🖼️⬇️
Volume={{ EXTERNAL_MEDIA_PATH }}:/mnt/external:ro
```

Change it to:

```plaintext
# External path to media 🖼️⬇️
Volume={{ EXTERNAL_MEDIA_PATH }}:/mnt/external:ro,z
```

This will add the `,z` option to the volume definition as needed.

**Comment by zuzzurro** [comment]
My question was more about avoiding having to make changes to something that is in git and therefore having to manage revisions and stashing and stuff. I thought the changes you had made went in that direction...

**Comment by Devbrat-Dev** [comment]
I’m not using SELinux, but I’ve now added the `z` flag to improve compatibility.
